### ISSUE TITLE
Expand API to utilize Recognition API

### ISSUE THREAD

**Issue by djshubs** [robmarkcole/simplehound#10]
The code utilizes Detection APIs, and it appears that SightHound also offers a Recognition API that would allow us to utilizer it for ALPR. 

Is this something that can be done, I'm not an expert coder but I'm willing to help to extend the functionality.

**Comment by dynasticorpheus** [comment]
Happy help test added ALPR functionality if needed.

**Comment by robmarkcole** [comment]
done
